# Generated by Django 5.2.3 on 2025-08-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_phone_order_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash on Delivery'), ('card', 'Credit/Debit Card'), ('bkash', 'bKash'), ('paypal', 'PayPal')], default='card', max_length=20),
        ),
    ]
