# Generated by Django 5.2.3 on 2025-08-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_tag_furnitureproduct_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnitureproduct',
            name='total_ratings',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='furnitureproduct',
            name='total_review',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
